# faster builds on new travis setup not using sudo
sudo: false

language: php

services:
  - memcached
  - mysql
  - postgresql

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version
            
  # initialize database
  - mysql -e "create database yii2_formgenerator_test"

script:
  - composer deploy-tests
  - composer run-tests
